### ISSUE TITLE
How to get rendered mask of a material part?

### ISSUE THREAD

**Issue by HospitableHost** [andyyankai/psdr-room#3]
Interesting work, thanks for your efforts in this research. I have a question, how to get rendered mask of a material part? In your paper section 4.4 - Crop pairs, you mentioned the rendered mask, so how do you get this. I know each mode in 3D-FUTURE have multiple material parts, and their offical renderer do not support this function. Do you use your PSDR-CUDA to do so? In your code, the var "obj_mask" seems to have something to do with rendered mask, but you just load from device. I'm really grateful to revice your response. Thanks so much.

**Comment by andyyankai** [comment]
the rendered mask you mentioned is in 
[per_obj_mask](https://github.com/andyyankai/psdr-room/tree/main/material_light_stage/input/63/texture_stage_init/per_obj_mask) folder correct?
These are simply to render per object group.
for example you can render [0.jpg](https://github.com/andyyankai/psdr-room/blob/main/material_light_stage/input/63/texture_stage_init/per_obj_mask/0.jpg) from [0_0.obj](https://github.com/andyyankai/psdr-room/blob/main/material_light_stage/input/63/texture_stage_init/0_0.obj)

I simply use psdr-jit to render all the .obj files in [texture_stage_init](https://github.com/andyyankai/psdr-room/tree/main/material_light_stage/input/63/texture_stage_init) (from the optimized result from object stage)

you can load all that obj file in any renderer to generate the mask per object
for example
```
for mm in range(num_obj):
    img = psdr_jit.FieldExtractionIntegrator(f"silhouette {mm}").renderC(sc, 0).numpy().reshape((sc.opts.height, sc.opts.width, 3))
```
while {mm} is the id of mesh in the scene to render that mask

I can also release some utility script for psdr-jit if need (maybe end of Dec)

**Comment by HospitableHost** [comment]
@andyyankai Hey, thanks for your reply. The object level mask is easily to be rendered. They are just like instance segmentation. But if a object has multiple material parts, how to render the mask of the specific material part?(The objects in 3D-FUTURE have multiple material parts, e.g. the mesh of a bed has more than one material parts)
![mmexport1701530553483](https://github.com/andyyankai/psdr-room/assets/44576391/204de3f0-a876-4c9b-8c7f-41d797078f7e)
And in your paper, you mentioned the material part.
Looking forward to your reply.

**Comment by andyyankai** [comment]
The model in the dataset have multiple material part for each mesh. You will need to spilt them first. I write a script to spilt that obj file(with material part) into multiple obj files(each only have the vertex and face for a single material group)
For example, the input data 0.obj is the whole mesh, and 0_0.obj 0_1.obj … are the split model for each material part. then just render those split model you will get per material mask

For the segmentation(from prediction). We don’t need per part segmentation(since target color can just be set by overlap the mask with the object mask and choose a medium color)

**Comment by andyyankai** [comment]
This is what you might need: [split_mesh.py](https://github.com/andyyankai/psdr-room/blob/main/helper_scripts/split_mesh.py)

**Comment by HospitableHost** [comment]
@andyyankai Thank you so much, what a clever way!

**Comment by HospitableHost** [comment]
@andyyankai Sorry to bother you again. I still have some questions.
1. What is the difference between (the 0bd81869-830e-4673-bfeb-e4d1e5c60302.obj in the obj_stage_init folder) and (the normalized_model.obj or raw_model.obj in obj_raw folder)?
2. Why the 74 line in the code is `v_group[:,1] -= v_model[:,1].min()` not `v_group[:,1] -= cy`?
3. Why the 81 line in the code do the operation `v_group /= dsize`?
4. Why the 83 line in the code do the operation `v_group[:,1] += vv_min`?
Thanks for your warm response! I'm really grateful.

**Comment by andyyankai** [comment]
1.  the obj_raw folder is simply the input data from 3d_future dataset, the {model_id}.obj file is generate using the following script:
```
v_model, tc, _, f_model, ftc, _ = igl.read_obj(str(obj_raw_path/model_key/"normalized_model.obj"))
cx = (v_model[:,0].min() + v_model[:,0].max()) / 2
cy = (v_model[:,1].min() + v_model[:,1].max()) / 2
cz = (v_model[:,2].min() + v_model[:,2].max()) / 2
v_model[:,0] -= cx
v_model[:,1] -= v_model[:,1].min()
v_model[:,2] -= cz
dsize =  max(v_model[:,0].max()-v_model[:,0].min(), 
             v_model[:,1].max()-v_model[:,1].min(), 
             v_model[:,2].max()-v_model[:,2].min())

v_model /= dsize
write_obj(obj_stage_init_path / f"{model_key}.obj", v_model, f_model, tc=tc, ftc=ftc)
```
This is simply preprocess the model so I can use it easily. (psdr-jit cant handle things like material group in obj file)

2. reason for line 74 is because we want to make sure the bottom of the model Y axis is at 0 unit. Also we want to make sure the model center of XY is at the center of model as well. So doing scaling/transform/rotate can be more easily. (for example, if we do scaling for a model with minimum Y value = 0, it will never float above the floor or below the floor)

3. I think is just want to make sure the size of the model is about 1.0 world unit

4. same as 2, just to ensure the minimum of Y axis is at 0.
