### ISSUE TITLE
How to distinguish different wall surfaces in the room stage?

### ISSUE THREAD

**Issue by qijiyaolinZGH** [andyyankai/psdr-room#6]
The semantic segmentation method mentioned in the paper is mask2former. However, when using it for panoptic segmentation, different wall surfaces in the results are merged instead of being separated into multiple wall surfaces. This issue can lead to the inability to estimate multiple wall surfaces in subsequent steps. How do you handle this problem?

**Comment by qijiyaolinZGH** [comment]
Will you release the code for room stage?

**Comment by andyyankai** [comment]
Most segmentation won’t give you split wall. I do tried some other methods such as http://xufeng.site/publications/2020/3D%20Room%20Layout%20Estimation%20from%20a%20Single%20RGB%20Image.pdf but give up since merge those code cost too much work.

In the end, the wall are splited using the normal map discontinuity (predicted) of the wall (same as the photoscene paper, not sure if this is mentioned in the paper). You first predict a normal map of the image and you should easily split the wall segmented normal map using how many discontinuous pieces. After the split do an erosion on the mask. This step is a fully computer vision level preprocessing.

**Comment by andyyankai** [comment]
Script to split the wall mask(from photoscene) https://github.com/ViLab-UCSD/PhotoScene/blob/67c93583adbaf14b7834e66b19541063f6046011/photoscene/preprocess.py#L204C3-L204C3

I might not have time recently to update the repo this month but I will try to find some time for that next month…

**Comment by qijiyaolinZGH** [comment]
Thanks!
